apiVersion: v1
kind: Service
metadata:
  name: taskflow-frontend
  namespace: taskflow
  labels:
    app: taskflow-frontend
spec:
  type: NodePort
  selector:
    app: taskflow-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
