apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: taskflow
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: changeMeInProd123
  MONGO_URI: mongodb://admin:changeMeInProd123@mongodb:27017/taskflow?authSource=admin
